# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install nvm
      run: |
        $NVM_HOME="$((Get-Location).Path)\mynvm"
        $env:NVM_HOME=$NVM_HOME
        $env:NVM_PATH=$NVM_HOME
        $env:NVM_SYMLINK="$NVM_HOME\nodejs"
        $Env:Path += ";$NVM_HOME"
        Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-noinstall.zip -OutFile nvm.zip
        Expand-Archive nvm.zip -DestinationPath "$NVM_HOME"
        New-Item -Path "$NVM_HOME\settings.txt" -ItemType File 
        echo "SETUP_NODE_NVM_NVM: $NVM_HOME"
        echo "SETUP_NODE_NVM_NODE: $NVM_HOME\nodejs\node.exe"
        echo "SETUP_NODE_NVM_NPM: $NVM_HOME\nodejs\npm.cmd"
    - name: Run tests
      run: |
       powershell
       cmd/test-ci.ps1 
